// <auto-generated />
using System;
using GaiaPins.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GaiaPins.Migrations
{
    [DbContext(typeof(PinsDbContext))]
    [Migration("20190619202701_NSFW")]
    partial class NSFW
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10");

            modelBuilder.Entity("GaiaPins.Data.GuildInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IncludeNSFW");

                    b.Property<long>("PinsChannelId");

                    b.Property<long>("WebhookId");

                    b.Property<string>("WebhookToken");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("GaiaPins.Data.PinnedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GuildId");

                    b.Property<long?>("GuildInfoId");

                    b.Property<long>("NewMessageId");

                    b.HasKey("Id");

                    b.HasIndex("GuildInfoId");

                    b.ToTable("PinnedMessage");
                });

            modelBuilder.Entity("GaiaPins.Data.PinnedMessage", b =>
                {
                    b.HasOne("GaiaPins.Data.GuildInfo", null)
                        .WithMany("PinnedMessages")
                        .HasForeignKey("GuildInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
